### ISSUE TITLE
Some question about Class similarity weighted knowledge distillation？

### ISSUE THREAD

**Issue by jainie-max** [HieuPhan33/REMINDER#1]
Hi， great work！ I have some questions about the  Class similarity weighted knowledge distillation.
As shown in eq. 8, (1). is it assigned the weight to output when the label belongs to the new classes?
（2). when the pseudo label belongs to the old classes and the similarity s is large than the threshold, is it reweight the output O_{i,v}^{t-1}?

**Comment by HieuPhan33** [comment]
Hi @jainie-max, thanks for your interest. 

In our current implementation, we only reweigh the labels belonging to the new classes. In other words, we don't reweigh the pseudo-labels belonging to the old classes.

You can see the variable `mask_fg` in Line 435 in `train.py`. It masks out outputs that belong to the old classes.

**Comment by jainie-max** [comment]
@HieuPhan33  Tanks, I get it!
