### ISSUE TITLE
Question about the background class.

### ISSUE THREAD

**Issue by kona419** [HieuPhan33/REMINDER#12]
Hello,
In pascalVOC dataset, 0th class is background. 
Does REMINDER make prototype for 0th class too?
Also, while calculate the similarity, does new class calculate with the 0th class?
If not, I want to know the part of excluding the 0th class in your code.

Thank you~

**Comment by HieuPhan33** [comment]
Hi @kona419,

Our current code does not exclude 0th class.  
We still treat 0th class as one of the old classes and doesn't have any special treatments for the background class.
Thanks for raising this interesting question!


As your suggestion, we hypothesize that excluding 0th class can circumvent the background shift problems. 
An even better solution is to capture the common background concepts between task t and task t-1, then only distill the output of that consistent-background class.

Thanks for being interested in our work.
Cheers.

**Comment by kona419** [comment]
> Hi @kona419,
> 
> Our current code does not exclude 0th class. We still treat 0th class as one of the old classes and doesn't have any special treatments for the background class. Thanks for raising this interesting question!
> 
> As your suggestion, we hypothesize that excluding 0th class can circumvent the background shift problems. An even better solution is to capture the common background concepts between task t and task t-1, then only distill the output of that consistent-background class.
> 
> Thanks for being interested in our work. Cheers.

Thanks for the reply!

You mean, find the background that includes neither task t nor task t-1, which does not have any meaningful objects, and distill that nothing-background class?

I cannot understand why we should distill the nothing-background class.

Thank you~

**Comment by HieuPhan33** [comment]
1) Why we need to distill background class:
The answer depends on your objective. 
We need to distill when we are interested in getting the background segmentation correct, taking self-driving car as an example, misclassifying the background as a road can force the car driving to non-road areas. 
However, we should not distill when we do not care about background segmentation, i.e., even misclassifying them as foreground classes is acceptable.

2) Paper writing.
Sincerely apologize for the confusion. We should include both C^(1:t-1) and background class c_b in Eq (10). We mistakenly overlook the notations when writing the equation.

**Comment by kona419** [comment]
> 1. Why we need to distill background class:
>    The answer depends on your objective.
>    We need to distill when we are interested in getting the background segmentation correct, taking self-driving car as an example, misclassifying the background as a road can force the car driving to non-road areas.
>    However, we should not distill when we do not care about background segmentation, i.e., even misclassifying them as foreground classes is acceptable.
> 2. Paper writing.
>    Sincerely apologize for abusing the notations. We should include both C^(1:t-1) and background class c_b in Eq (10). We mistakenly overlook the notations when writing the equation.

Thank you for your kind response! :)
