### ISSUE TITLE
Issue Regarding Table 5

### ISSUE THREAD

**Issue by Ze-Yang** [HieuPhan33/REMINDER#5]
Hi @HieuPhan33, I have tried completely removing the additional KD loss, i.e. `CSW-KD removed`. The results shown below are still higher than UNKD and Knowledge Distillation in Table 5. Therefore, I doubt the authenticity of the ablation in Table 5. It's unlikely to get such low results since the intermediate layer KD as well as the final small-scale output KD proposed by PLOP are still in place.

|            | 0-15 | 16-20 |  all |
|-----|:------:|:-------:|:------:|
| Reported   | 68.30 | 27.23 | 58.52 |
| Reproduced | 66.37 | 27.03 | 57.00 |
| CSW-KD removed | 61.97 | 27.87 | 53.85 |

**Comment by HieuPhan33** [comment]
Hi, could you please share with me the script you use for UNKD?

UNKD means there "no" output KD applied. Only POD loss and CE loss are applied.

This is the script I used for UNKD: [reminder_15-1_unkd.txt](https://github.com/HieuPhan33/REMINDER/files/9421296/reminder_15-1_unkd.txt)

I just re-run it, and the mIoU is 28.71%.

**Comment by HieuPhan33** [comment]
UNKD is not compatible with POD loss. 
Based on my previous experiments, applying both UNKD and POD will reduce the performance of PLOP.

I will try to re-run the experiments and share with you the results soon.

**Comment by Ze-Yang** [comment]
Thank you for the reply. I will also try to run with UNKD and update you soon.

**Comment by HieuPhan33** [comment]
I only get 40.57% for UNKD.
Here is the script I used
[unkd_15-1.txt](https://github.com/HieuPhan33/REMINDER/files/9421914/unkd_15-1.txt)
:

**Comment by Ze-Yang** [comment]
Please try with this [script](https://github.com/HieuPhan33/REMINDER/files/9422054/reminder_15-1.txt). I notice that some arguments are omitted in your script, e.g., `pod_options`, `classif_adaptive_factor`, `threshold`, `init_balanced`, while `pod_factor = 0.01` is mis-specified as 0.001.

**Comment by Ze-Yang** [comment]
I have obtained the results for UNKD with the above script. The mIoU turned out to be 55.72, fairly higher than the reported 50.29.

|    Codebase   |   Method  | 0-15 | 16-20 |  all |
|-----|-----|:------:|:-------:|:------:|
| REMINDER | REMINDER (Reported)   | 68.30 | 27.23 | 58.52 |
| REMINDER | REMINDER (Reproduced) | 66.37 | 27.03 | 57.00 |
| REMINDER | CSW-KD removed | 61.97 | 27.87 | 53.85 |
| REMINDER | UNKD | 66.50 | 21.23 | 55.72 |

**Comment by HieuPhan33** [comment]
Thanks @Ze-Yang, indeed I get the result mIoU 54.98%.

Yes, I made a mistake when setting the hyper-parameters for UNKD. That's why the reported result is not optimal.

I will update the latest result of Table 5 right in this github repo.

Thanks for pointing it out.
