### ISSUE TITLE
issue when compute_prototype

### ISSUE THREAD

**Issue by hubblezhang** [HieuPhan33/REMINDER#6]
line 26, in train.py, we can see:
`   seg = seg.view(-1)
    features = features.transpose(1, 3).contiguous().view(B * H * W, -1)
    for c in classes:
        selected_features = features[seg == c]`
As you know, before I run these lines, the dimension of seg is [B, H, W], and features is [B, C, H, W]. After I run '.transpose(1, 3)', seg is flatten to [BHW], but features is [BWH, C], is that correct? I think selected features do not correspond to seg one to one, because the shape of features is [B, W, H, C] not [B, H, W, C] after '.transpose(1,3)'. Dose transpose(1, 3) should be replaced by permute([0, 2, 3, 1])?

**Comment by HieuPhan33** [comment]
Yes, you are right.

The latest version use 'permute([0,2,3,1])'. 

I forgot to correct this Line before pushing to Git.
