### ISSUE TITLE
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [10, 512, 512, 3]

### ISSUE THREAD

**Issue by HYUNMIN-HWANG** [HieuPhan33/REMINDER#7]
When I run the REMINDER/scripts/ade/reminder_100-10.sh

I got the error like below: 
`Traceback (most recent call last):
  File "run.py", line 585, in <module>
    main(opts)
  File "run.py", line 156, in main
    val_score = run_step(opts, world_size, rank, device)
  File "run.py", line 427, in run_step
    logger=logger
  File "/root/REMINDER/train.py", line 362, in train
    loss = criterion(outputs, labels)  # B x H x W
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [10, 512, 512, 3]
`

When I checked the shape, labels.shape = [10, 512, 512, 3] but outputs.shape = [10, 101, 512, 512] 

How can I matched the same shape with labels and outputs?

**Comment by HieuPhan33** [comment]
`labels` should have a size of [10, 512, 512] not [10, 512, 512, 3].

You probably load the `labels` file as an RGB image not as grayscale, thus leading to 3 channels at the last dimension.

There are a few things you could do.
On Line 66 in [ade.py](https://github.com/HieuPhan33/REMINDER/blob/f8b67153c6d9e5ad813f0a43bf6e71525a3001b1/dataset/ade.py#L66), please check if the size of `target` is [10, 512, 512].

If the size is [10, 512, 512, 3], please check the following.
1) Check the filename to see if it correctly links to label map `ADEChallengeData2016/training/ADE_train_00019928.png`.
2) Open the label file to see if it is grayscale (not RGB with colours).
3) If the file is indeed grayscale, probably PIL does not recognize the format and incorrectly load RGB format. Force RGB-to-gray conversion using this code: `Image.open(self.images[index][1]).convert('L')`.

**Comment by HieuPhan33** [comment]
`labels` should have a size of [10, 512, 512] not [10,512,512,3].

You probably load the label file using the RGB format, leading to the additional 3 channels at the last dimension.
The label file should be loaded as a grayscale image.
On Line 66 in [ade.py](https://github.com/HieuPhan33/REMINDER/blob/f8b67153c6d9e5ad813f0a43bf6e71525a3001b1/dataset/ade.py#L66), check if the `target` variable has a size [10, 512, 512].

If the size is [10, 512, 512, 3], you can check the following.
1) Check the file name to see if it correctly points the ADE20k label file under ADEChallengeData2016/annotations/training.
2) Open the image file, check if it is grayscale (not RGB colour).
3) If it is gray, but PIL loads as RGB. Force RGB-to-gray conversion using this code: `img = Image.open(self.images[index][1]).convert('L')`

**Comment by HYUNMIN-HWANG** [comment]
> `labels` should have a size of [10, 512, 512] not [10,512,512,3].
> 
> You probably load the label file as RGB, leading to the additional 3 channels at the last dimension. The label file should be loaded as a grayscale image. On Line 66 in [ade.py](https://github.com/HieuPhan33/REMINDER/blob/f8b67153c6d9e5ad813f0a43bf6e71525a3001b1/dataset/ade.py#L66), check if the `target` variable has a size [10, 512, 512].
> 
> If the size is [10, 512, 512, 3], you can check the following.
> 
> 1. Check the file name to see if it correctly points the ADE20k label file under ADEChallengeData2016/annotations/training.
> 2. Open the image file, check if it is grayscale (not RGB colour).
> 3. If it is gray, but PIL loads as RGB. Force RGB-to-gray conversion using this code: `target = Image.open(self.images[index][1]).convert('L')`

Great.
Thanks a lot. I solved the problem.
