### ISSUE TITLE
errata in /ade/reminder sh files

### ISSUE THREAD

**Issue by jcy132** [HieuPhan33/REMINDER#8]
In the sh files for ade dataset, (reminder_100_50.sh, reminder_50.sh, reminder_100-10.sh, reminder_100-10.sh)

METHOD is set as FT, not the REMINDER.
( METHOD = FT )

maybe errata?

**Comment by HieuPhan33** [comment]
Setting the parameters "--csw_kd ${LOSS} --delta_csw 1.0" makes the model uses CSW loss, i.e., following REMINDER framework.

I set 'FT' method to freely adjust the hyper-parameters for ADE20k dataset.
